// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:efe05753-f8a6-4e2f-a1ab-fe4a0b17c64d",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_MdXJsq1J5",
    "aws_user_pools_web_client_id": "6rkf3aapqlueoajajl6rk1jkn6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://itpu3bisknarjd7pb3b37qn7dm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "riders-square-develop",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://riders-square-develop.s3-website-ap-northeast-1.amazonaws.com",
    "Auth": {
        "region": "ap-northeast-1",
        "userPoolId": "ap-northeast-1_3lRCkgpVL",
        "userPoolWebClientId": "2b3q9qa4acbhj1ipn63i1fldpa"
    }
};


export default awsmobile;
