// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "rider-square-dev",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://rs-dev-tools.commude.biz/",
    "aws_cognito_identity_pool_id": null,
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_MH9VZ4UdY",
    "aws_user_pools_web_client_id": "1aa035sb5p1s10kspvsrdq471l",
    "oauth": {
        "domain": "riders-square-dev.auth.ap-northeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://rs-dev-tools.commude.biz/",
        "redirectSignOut": "https://rs-dev-tools.commude.biz/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
